spring.application.name=group-project
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=2
spring.profiles.active=local

# Expose Spring Actuator Endpoints for Monitoring/Observability
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Enable http server request metrics bucket distributions (histograms) for APDEX
management.metrics.distribution.percentiles-boundary.http.server.requests=300ms,1s
management.metrics.distribution.histogram.http.server.requests=true