spring.application.name=group-project

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:postgres.mhmorluiqvgnomzfcxtx}
spring.datasource.password=${DB_PASSWORD_PROD:eKhos4vA6HyuqzZw}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

logging.level.root=WARN
logging.level.id.ac.ui.cs.advprog.groupproject=INFO

server.error.include-message=never
server.error.include-stacktrace=never