global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-actuator'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      # Staging (best practice: avoid hitting production directly)
      - targets: ['json-staging-cdf3ecf67eca.herokuapp.com']
